name: 'Mid Phase'
description: 'Triggers a zap and nikto scan via API and fails on critical findings.'

inputs:
  target_url:
    description: 'Target GitHub repository or deployed URL'
    required: true
  user_id:
    description: 'User ID for the scan request'
    required: true
  project_id:
    description: 'Project ID for the scan request'
    required: true
  api_url:
    description: 'API URL to trigger the scan'
    required: true
  api_token:
    description: 'Bearer token for authorization'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Trigger Scans
      shell: bash
      run: |
        echo "🚀 Triggering scans..."

        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "${{ inputs.api_url }}" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ inputs.api_token }}" \
          -d '{
                "target_url": "${{ inputs.target_url }}",
                "user_id": "${{ inputs.user_id }}",
                "project_id": "${{ inputs.project_id }}"
              }')

        STATUS_CODE=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')

        STATUS=$(echo "$BODY" | jq -r '.status // empty')
        MESSAGE=$(echo "$BODY" | jq -r '.message // empty')
        REPORT_URL=$(echo "$BODY" | jq -r '.report_url // empty')

        echo "ℹ️ Status: $STATUS"
        echo "ℹ️ Message: $MESSAGE"

        if [ "$STATUS_CODE" = "422" ] || [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "ERROR" ]; then
          echo "❌ Scan failed. See report: $REPORT_URL"
          exit 1
        fi

        echo "✅ Scan completed successfully. Report: $REPORT_URL"
