name: 'Pre Phase Scan'
description: 'Triggers pre-deployment scan and fails on critical findings.'

inputs:
  target_url:
    required: true
  user_id:
    required: true
  project_id:
    required: true
  api_token:
    required: true
  pat:
    required: false
  branch:
    required: false

runs:
  using: 'composite'
  steps:
    - name: Trigger & Monitor Pre-Scan
      shell: bash
      run: |
        echo "::group::🚀 Triggering Pre-Scan"

        BRANCH="${{ inputs.branch:-}}"
        PAT="${{ inputs.pat:-}}"

        PAYLOAD=$(jq -n \
          --arg url "${{ inputs.target_url }}" \
          --arg uid "${{ inputs.user_id }}" \
          --arg pid "${{ inputs.project_id }}" \
          --arg pat "$PAT" \
          --arg branch "$BRANCH" '
          {target_url: $url, user_id: $uid, project_id: $pid}
          + (if ($pat | length) > 0 then {pat_token: $pat} else {} end)
          + (if ($branch | length) > 0 then {branch: $branch} else {} end)')

        RESPONSE=$(curl -s -w "\n%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ inputs.api_token }}" \
          -d "$PAYLOAD" \
          "https://hashsecured.com/backend/scan/pre-request")

        STATUS=$(echo "$RESPONSE" | tail -n1)
        BODY=$(echo "$RESPONSE" | sed '$d')
        EVENT_ID=$(echo "$BODY" | jq -r '.event_id // empty')
        MESSAGE=$(echo "$BODY" | jq -r '.message // empty')

        if [ "$STATUS" != "200" ] || [ -z "$EVENT_ID" ]; then
          echo "::error::Failed to trigger scan: $MESSAGE"
          exit 1
        fi

        echo "::endgroup::"
        echo "::group::⏳ Polling Scan Status"

        POLL_URL="https://hashsecured.com/backend/scan/scan-status?event_id=$EVENT_ID&user_id=${{ inputs.user_id }}"
        ATTEMPTS=30
        INTERVAL=10
        TOTAL_TIME=$((ATTEMPTS * INTERVAL))

        for i in $(seq 1 $ATTEMPTS); do
          POLL=$(curl -s -X GET -H "Authorization: Bearer ${{ inputs.api_token }}" "$POLL_URL")
          STATUS_NOW=$(echo "$POLL" | jq -r '.status // empty')

          ELAPSED=$((i * INTERVAL))
          REMAIN=$((TOTAL_TIME - ELAPSED))
          PERCENT=$(( (ELAPSED * 100) / TOTAL_TIME ))
          FILLED=$((PERCENT / 5))
          EMPTY=$((20 - FILLED))

          case "$STATUS_NOW" in
            COMPLETED) BLOCK="🟩" ;;
            FAILED) BLOCK="🟥" ;;
            *) BLOCK="🟨" ;;
          esac

          BAR="$(printf "$BLOCK%.0s" $(seq 1 $FILLED))$(printf "▫️%.0s" $(seq 1 $EMPTY))"

          echo -ne "\r⏳ [$BAR] $PERCENT% | Status: $STATUS_NOW | ${ELAPSED}s / ${TOTAL_TIME}s (ETA: ${REMAIN}s)"

          if [[ "$STATUS_NOW" == "COMPLETED" || "$STATUS_NOW" == "FAILED" ]]; then
            echo ""
            break
          fi
          sleep $INTERVAL
        done

        echo "::endgroup::"
        REPORT="https://hashsecured.com/summary/$EVENT_ID"

        echo ""
        echo "==============================="
        if [[ "$STATUS_NOW" == "COMPLETED" ]]; then
          echo "✅ PRE-SCAN COMPLETED SUCCESSFULLY"
          echo "🔗 Report: $REPORT"
          echo "==============================="
          echo "::notice::✅ Pre-scan complete: [View Report]($REPORT)"
        elif [[ "$STATUS_NOW" == "FAILED" ]]; then
          echo "❌ PRE-SCAN FAILED"
          echo "🔗 Report: $REPORT"
          echo "==============================="
          echo "::error::❌ Pre-scan failed: [View Report]($REPORT)"

          jq -c '.scan_summaries[]?' <<< "$POLL" | while read -r item; do
            TOOL=$(jq -r '.tool_name' <<< "$item")
            MSG=$(jq -r '.summary.message' <<< "$item")
            echo "::error::[$TOOL] $MSG"
          done
          exit 1
        else
          echo "⚠️ PRE-SCAN TIMED OUT"
          echo "🔗 Report: $REPORT"
          echo "==============================="
          echo "::warning::⚠️ Scan timed out after ${TOTAL_TIME}s. Status: $STATUS_NOW"
          exit 1
        fi
