runs:
  using: "docker"
  image: "docker://kirandockerch/hashsecured_actions:latest"
  entrypoint: python3
  args:
    - scan_action.py
    - --phase
    - ${{ inputs.phase }}
    - --target_url
    - ${{ inputs.target_url }}
    - --user_id
    - ${{ inputs.user_id }}
    - --project_id
    - ${{ inputs.project_id }}
    - --api_token
    - ${{ inputs.api_token }}
    - --branch
    - ${{ inputs.branch }}
    - --pat
    - ${{ inputs.pat }}
